const jsonfile = require('jsonfile');
const fg = require('fast-glob');
const path = require('upath');
const _ = require('lodash');
const fs = require('fs');

const initialFiles = fg.sync([path.join(__dirname, '../src/globals/svg/ico_*.svg')]);

initialFiles.forEach(file => {
	fs.renameSync(file, file.replace('ico_', ''), (error) => {
		if (error) throw error;
	})
});

const finalFiles = fg.sync([path.join(__dirname, '../src/globals/svg/*.svg')]);
const icons = finalFiles.map(file => {
	return _.last(file.split('/')).replace('.svg', '');
})

const className = getClassName();

let wstream = fs.createWriteStream(path.join(__dirname, '../src/docs/icons.stories.mdx'), { encoding: 'utf8' });
wstream.write(`
[//]: # (This file was autogenerated, don't edit!!!!)

import { Meta } from "@storybook/addon-docs/blocks";

# Correos Icons

<Meta title="DOCS/Icons" />
`);
wstream.write(`\n<div style={{padding: '0', display: 'flex', 'flexDirection': 'row', 'flexWrap': 'wrap'}}>\n`);
icons.forEach(icon => {
	wstream.write(`\t<div style={{'margin': '20px', padding: '20px 0 0', display: 'flex', 'flexDirection': 'column', 'justifyContent': 'center', 'fontSize': '0.875rem', 'justifyItems': 'center', 'alignContent': 'center', 'alignItems': 'center', 'flex': '20%', 'maxWidth': 'calc(20% - 40px)', 'borderRadius': '4px', 'background': '#f9f9f9', 'color': '#4a545f'}}>\n`);
	wstream.write(`\t\t<i className="${className}-${icon}"></i>\n`);
	wstream.write(`\t\t<span style={{'marginTop': '20px', 'padding': '10px 0', 'width': '100%', 'textAlign': 'center', 'background': '#f3f2f2'}}>${className}-${icon}</span>\n`);
	wstream.write('\t</div>\n');
});
wstream.write('</div>\n');
wstream.end();

// Functions
function getClassName() {
	const webfontConfig = jsonfile.readFileSync(path.join(__dirname, '../webfonts.json'));
	return (webfontConfig && webfontConfig.templateClassName) || 'icon';
}
